const games = [
    {
        name: "Cyberpunk 2077",
        surname: "cyberpunk",
        price: "59.99",
        desc: 'Cyberpunk 2077 là phần tiếp theo của Cyberpunk 2020, lấy bối cảnh thành phố Night City trong tương lai. Trò chơi theo chân V, một lính đánh thuê đang vươn lên trong thế giới đầy bạo lực và nguy hiểm.',
        link: 'https://www.cyberpunk.net/',
        downloadLink: 'https://play.google.com/store/apps/details?id=com.cdprojektred.cyberpunk2077companion',
        release: '10th of December, 2020',
        platforms: 'Playstation 4, PC, Xbox Series S/X, Playstation 5, Xbox One',
        genre: 'RPG',
        developers: 'CD PROJECT RED, CD PROJECT',
        publishers: 'CD PROJECT RED',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 78,
        id: 0,
        cover: "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_500/v1658188604/cyberpunk_n6jitl.jpg",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658188604/cyberpunk_n6jitl.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658235373/cyberpunk_1_s00vwf.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658235372/cyberpunk_2_mq46xm.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658235378/cyberpunk_3_fajdmi.jpg"
        ]
    },
    {
        name: "Battlefield V",
        surname: "battlefield",
        price: "29.99",
        desc: 'Battlefield V đưa người chơi trở lại Thế chiến thứ hai với các trận chiến đa người chơi hoành tráng và câu chuyện đơn đầy cảm xúc.',
        link: 'https://www.origin.com/store/battlefield/battlefield-v',
        downloadLink: 'https://www.ea.com/games/battlefield/battlefield-5/buy',
        release: '9th of November, 2018',
        platforms: 'Playstation 4, PC, Xbox Series S/X, Xbox One',
        genre: 'Shooter',
        developers: 'EA Digital Illusions CE',
        publishers: 'Electronic Arts',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 71,
        id: 1,
        cover: "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_500/v1658188621/battlefield_n0gd5a.jpg",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658188621/battlefield_n0gd5a.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658235437/battlefield_1_jpudhq.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658235437/battlefield_3_zy9ewv.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658235438/battlefield_2_txs230.jpg"
        ]
    },
    {
        name: "Life is Strange",
        surname: "lis",
        price: "14.99",
        desc: 'Life Is Strange là một trò chơi chia thành năm phần, nơi người chơi có thể quay ngược thời gian để thay đổi quá khứ, hiện tại và tương lai. Bạn sẽ vào vai Max, một học sinh nhiếp ảnh, khám phá những bí mật đen tối của Arcadia Bay.',
        link: 'https://lifeisstrange.square-enix-games.com/',
        downloadLink: 'https://store.steampowered.com/app/319630/Life_is_Strange/',
        release: '30th of January, 2015',
        platforms: 'Playstation 4, PC, Xbox One, Xbox 360, Playstation 3',
        genre: 'Adventure',
        developers: 'Dontnod Entertainment',
        publishers: 'Square Enix',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 83,
        id: 2,
        cover: "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_500/v1658188606/lis_ft0puo.jpg",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658188606/lis_ft0puo.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658236055/lis_1_rkrxt5.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658236272/lis_2_dcrdwz.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658236055/lis_3_komskf.jpg"
        ]
    },
    {
        name: "Mario Kart 8: Deluxe",
        surname: "mariokart",
        price: "24.99",
        desc: 'Mario Kart 8: Deluxe mang đến trải nghiệm đua xe vui nhộn với bạn bè, với chế độ chiến đấu được cải tiến và các nhân vật mới.',
        link: 'https://mariokart8deluxe.nintendo.com/',
        downloadLink: 'https://www.nintendo.com/store/products/mario-kart-8-deluxe-switch/',
        release: '28th of April, 2017',
        platforms: 'Nintendo Switch',
        genre: 'Racing',
        developers: 'Nintendo EAD',
        publishers: 'Nintendo',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 84,
        id: 3,
        cover: "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_500/v1658232678/mariokart_0_mhgbeg.jpg",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658232678/mariokart_0_mhgbeg.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658236315/mariokart_1_heekfq.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658236316/mariokart_3_yzhdje.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658236315/mariokart_2_peeyho.jpg"
        ]
    },
    {
        name: "BioShock Infinite",
        surname: "bioshockinfinite",
        price: "18.99",
        desc: 'BioShock Infinite là một trò chơi bắn súng góc nhìn thứ nhất, nơi người chơi vào vai Booker DeWitt để giải cứu một cô gái bị giam cầm trong thành phố nổi Columbia.',
        link: 'https://2k.com/en-US/game/bioshock-infinite/',
        downloadLink: 'https://store.steampowered.com/app/8870/BioShock_Infinite/',
        release: '26th of February, 2013',
        platforms: 'Xbox One, PlayStation 4, Linux, Xbox 360, PC, Nintendo Switch, PlayStation 3',
        genre: 'Puzzle',
        developers: 'Irrational Games',
        publishers: '2K Games',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 86,
        id: 4,
        cover: "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_500/v1658188602/bioshockinfinite_qyo3pi.jpg",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658188602/bioshockinfinite_qyo3pi.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658236359/bioshockinfinite_1_vutin0.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658236360/bioshockinfinite_2_bphusb.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658236361/bioshockinfinite_3_v1ckvh.jpg"
        ]
    },
    {
        name: "Anno: 1800",
        surname: "anno",
        price: "12.99",
        desc: 'Anno 1800 là một trò chơi xây dựng thành phố và chiến lược, lấy bối cảnh thế kỷ 19 trong thời kỳ Cách mạng Công nghiệp.',
        link: 'https://anno-union.com/',
        downloadLink: 'https://store.ubisoft.com/gb/anno-1800/5f0f6e310c8e7d0a0c0c0c0c.html',
        release: '16th of April, 2019',
        platforms: 'PC (Microsoft Windows)',
        genre: 'Strategy',
        developers: 'Blue Byte',
        publishers: 'Ubisoft',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 81,
        id: 5,
        cover: "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_500/v1658188622/anno_cbmzye.jpg",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658188622/anno_cbmzye.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658236405/anno_1_bpil6t.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658236405/anno_2_udh5ep.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658236405/anno_3_hoqcp0.jpg"
        ]
    },
    {
        name: "Red Dead Redemption 2",
        surname: "rdr",
        price: "34.99",
        desc: 'Red Dead Redemption 2 kể về câu chuyện của Arthur Morgan và băng đảng Van der Linde trong thời kỳ cuối của miền Tây hoang dã.',
        link: 'https://www.rockstargames.com/reddeadredemption2',
        downloadLink: 'https://store.steampowered.com/app/1174180/Red_Dead_Redemption_2/',
        release: '26th of October, 2018',
        platforms: 'Xbox One, PlayStation 4, PC, Google Stadia',
        genre: 'RPG',
        developers: 'Rockstar Studios',
        publishers: 'Rockstar Games',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 92,
        id: 6,
        cover: "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_500/v1658188613/rdr_fhqs3d.jpg",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,w_1920/v1658188613/rdr_fhqs3d.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658236494/rdr_3_euhfwh.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658236495/rdr_2_aodums.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658236494/rdr_1_v6xhov.jpg"
        ]
    },
    {
        name: "Horizon Zero Dawn",
        surname: "horizon",
        price: "29.99",
        desc: 'Horizon Zero Dawn lấy bối cảnh thế giới hậu tận thế, nơi các cỗ máy khổng lồ thống trị. Người chơi sẽ vào vai Aloy, một thợ săn dũng cảm.',
        link: 'https://www.guerrilla-games.com/games',
        downloadLink: 'https://store.steampowered.com/app/1151640/Horizon_Zero_Dawn_Complete_Edition/',
        release: '28th of February, 2017',
        platforms: 'PlayStation 4, PC',
        genre: 'Adventure',
        developers: 'Guerrilla Games',
        publishers: 'Sony Interactive Entertainment',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 90,
        id: 7,
        cover: "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_500/v1658188606/horizon_jzlhsd.jpg",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658188606/horizon_jzlhsd.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658236576/horizon_3_vwjcpi.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658236574/horizon_2_ara05m.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658236574/horizon_1_johwym.jpg"
        ]
    },
    {
        name: "Grand Theft Auto: V",
        surname: "gtav",
        price: "39.99",
        desc: 'Grand Theft Auto V là một trò chơi thế giới mở rộng lớn, nơi người chơi có thể khám phá thành phố Los Santos và tham gia vào các nhiệm vụ đầy kịch tính.',
        link: 'https://www.rockstargames.com/gta-v',
        downloadLink: 'https://store.steampowered.com/app/271590/Grand_Theft_Auto_V/',
        release: '17th of September, 2013',
        platforms: 'Xbox One, PlayStation 4, Xbox 360, PlayStation 5, PC, PlayStation 3, Xbox Series S/X',
        genre: 'Action',
        developers: 'Rockstar North',
        publishers: 'Rockstar Games',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 90,
        id: 8,
        cover: "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_500/v1658188604/gtav_x1ccio.jpg",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658188604/gtav_x1ccio.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658236641/gtav_1_gkelkb.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658236641/gtav_3_dswcgm.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658236641/gtav_2_b1xno6.jpg"
        ]
    },
    {
        name: "The Elder Scrolls: Skyrim",
        surname: "skyrim",
        price: "19.99",
        desc: 'The Elder Scrolls: Skyrim đưa người chơi vào cuộc phiêu lưu trong thế giới giả tưởng, nơi bạn là Dovahkiin, người được định mệnh để đánh bại rồng Alduin.',
        link: 'https://elderscrolls.bethesda.net/de/',
        downloadLink: 'https://store.steampowered.com/app/72850/The_Elder_Scrolls_V_Skyrim/',
        release: '10th of November, 2011',
        platforms: 'Xbox 360, PC (Microsoft Windows), PlayStation 3',
        genre: 'RPG',
        developers: 'Bethesda Game Studios',
        publishers: 'Bethesda Softworks',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 88,
        id: 9,
        cover: "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_500/v1658584215/skyrim_js5pmg.jpg",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658584215/skyrim_js5pmg.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658583241/skyrim_1_ludikr.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658583241/skyrim_2_zgnhf5.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658584731/maxresdefault_mciyjz.jpg"
        ]
    },
    {
        name: "Warframe",
        surname: "warframe",
        price: "5.99",
        desc: 'Warframe là một trò chơi hành động, nơi người chơi vào vai các chiến binh Tenno để chiến đấu chống lại Đế chế Grineer.',
        link: 'https://www.warframe.com/de/landing',
        downloadLink: 'https://www.warframe.com/download',
        release: '25th of March, 2013',
        platforms: 'Xbox One, PlayStation 4, PlayStation 5, PC, Nintendo Switch, Xbox Series S/X',
        genre: 'Action',
        developers: 'Digital Extremes',
        publishers: 'Digital Extremes',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 76,
        id: 10,
        cover: "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_500/v1658188601/warframe_kghu8g.jpg",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658188601/warframe_kghu8g.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658236676/warframe_3_t2bwvx.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658236676/warframe_2_ihvoqj.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658236674/warframe_1_txaury.jpg"
        ]
    },
    {
        name: "Minecraft",
        surname: "minecraft",
        price: "25.99",
        desc: 'Minecraft cho phép người chơi khám phá, tương tác và xây dựng trong một thế giới mở được tạo ngẫu nhiên.',
        link: 'https://www.minecraft.net',
        downloadLink: 'https://play.google.com/store/apps/details?id=com.mojang.minecraftpe',
        release: '15th of August, 2011',
        platforms: 'Android, Linux, Mac, PC',
        genre: 'Adventure',
        developers: 'Mojang',
        publishers: 'Mojang / Xbox Game Studios / Sony Interactive Entertainment',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 84,
        id: 11,
        cover: "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_500/v1658188606/minecraft_iuejtm.jpg",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658188606/minecraft_iuejtm.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658236747/minecraft_2_pqo4tv.png",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658236749/minecraft_1_vyp8bd.png",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658236744/minecraft_3_cea2dc.png"
        ]
    },
    {
        name: "Rise of the Tomb Raider",
        surname: "riseofthetombraider",
        price: "12.99",
        desc: 'Rise of the Tomb Raider theo chân Lara Croft trong hành trình khám phá thành phố huyền thoại Kitezh và chiến đấu với kẻ thù.',
        link: 'https://tombraider.square-enix-games.com/en-us',
        downloadLink: 'https://store.steampowered.com/app/391220/Rise_of_the_Tomb_Raider/',
        release: '10th of November, 2015',
        platforms: 'Xbox One, PlayStation 4, Linux, Xbox 360, Mac, PC, Google Stadia',
        genre: 'Adventure',
        developers: 'Crystal Dynamics',
        publishers: 'Microsoft Studios / Square Enix Europe',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 82,
        id: 12,
        cover: "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_500/v1658188610/riseofthetombraider_uq2q6t.jpg",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658188610/riseofthetombraider_uq2q6t.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658236831/riseofthetombraider_2_vvhbqe.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658236829/riseofthetombraider_1_bq8avn.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658236830/riseofthetombraider_3_xm9ggz.jpg"
        ]
    },
    {
        name: "Metro Exodus",
        surname: "metro",
        price: "37.99",
        desc: 'Metro Exodus là một trò chơi bắn súng góc nhìn thứ nhất, nơi người chơi khám phá vùng hoang dã nước Nga và chiến đấu để sinh tồn.',
        link: 'https://www.metrothegame.com/de/',
        downloadLink: 'https://store.steampowered.com/app/412020/Metro_Exodus/',
        release: '15th of February, 2019',
        platforms: 'Xbox One, PlayStation 4, PlayStation 5, PC, Xbox Series S/X, Google Stadia',
        genre: 'Shooter',
        developers: '4A Games',
        publishers: 'Deep Silver',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 83,
        id: 13,
        cover: "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_500/v1658188608/metro_o45ytf.jpg",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658188608/metro_o45ytf.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658236875/metro_1_mseeps.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658236878/metro_2_wtk9ux.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658236875/metro_3_y6ux12.jpg"
        ]
    },
    {
        name: "Terraria",
        surname: "terraria",
        price: "14.99",
        desc: 'Terraria là một trò chơi phiêu lưu, nơi người chơi có thể đào bới, chiến đấu, khám phá và xây dựng trong một thế giới mở.',
        link: 'https://terraria.org/',
        downloadLink: 'https://play.google.com/store/apps/details?id=com.and.games505.TerrariaPaid',
        release: '16th of May, 2011',
        platforms: 'A lot.',
        genre: 'Adventure',
        developers: 'Re-Logic',
        publishers: '505 Games',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 81,
        id: 14,
        cover: "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_500/v1658188609/terraria_yb3iuc.jpg",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658188609/terraria_yb3iuc.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658236904/terraria_1_sw79la.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658236905/terraria_2_kqpdyq.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658236905/terraria_3_wghczh.jpg"
        ]
    },
    {
        name: "Rocket League",
        surname: "rocketleague",
        price: "23.99",
        desc: 'Rocket League kết hợp giữa bóng đá và xe hơi, mang đến trải nghiệm chơi game độc đáo và thú vị.',
        link: 'https://www.rocketleague.com/',
        downloadLink: 'https://store.epicgames.com/en-US/p/rocket-league',
        release: '7th of July, 2015',
        platforms: 'Xbox One, PlayStation 4, Linux, Mac, PlayStation 5, PC, Nintendo Switch, Xbox Series S/X',
        genre: 'Sports',
        developers: 'Psyonix',
        publishers: 'Psyonix',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 83,
        id: 15,
        cover: "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_500/v1658188608/rocketleague_on6yqd.jpg",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,w_1920/v1658188608/rocketleague_on6yqd.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658236932/rocketleague_2_oogr9i.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658236933/rocketleague_3_s6klzw.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658236929/rocketleague_1_qcslm3.jpg"
        ]
    },
    {
        name: "The Witcher 3: Wild Hunt",
        surname: "thewitcher",
        price: "19.99",
        desc: 'The Witcher 3: Wild Hunt theo chân Geralt of Rivia trong hành trình tìm kiếm người yêu cũ và đối mặt với các thế lực nguy hiểm.',
        link: 'https://www.thewitcher.com/en',
        downloadLink: 'https://store.steampowered.com/app/292030/The_Witcher_3_Wild_Hunt/',
        release: '19th of May, 2015',
        platforms: 'Xbox One, PlayStation 4, PC, Nintendo Switch',
        genre: 'RPG',
        developers: 'CD PROJECT RED',
        publishers: 'CD PROJECT',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 95,
        id: 16,
        cover: "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_500/v1658188610/thewitcher_tllr60.jpg",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658188610/thewitcher_tllr60.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658236962/thewitcher_2_tipggu.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658237770/witcher1_zgg86b.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658236962/thewitcher_3_kyoymo.jpg"
        ]
    },
    {
        name: "Hitman",
        surname: "hitman",
        price: "12.99",
        desc: 'Hitman là một trò chơi chiến lược, nơi người chơi vào vai sát thủ Agent 47 để thực hiện các nhiệm vụ ám sát.',
        link: 'https://hitman.com/global/',
        downloadLink: 'https://store.steampowered.com/app/236870/HITMAN/',
        release: '11th of March, 2016',
        platforms: 'Xbox One, PlayStation 4, Linux, Mac, PC, Google Stadia',
        genre: 'Strategy',
        developers: 'IO Interactive',
        publishers: 'Square Enix Europe',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 81,
        id: 17,
        cover: "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_500/v1658188605/hitman_pqhnm6.jpg",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658188605/hitman_pqhnm6.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658237949/hitman_yj2now.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658237835/hitman_2_s3d61k.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658237835/hitman_1_ny5whm.jpg"
        ]
    },
    {
        name: "Fallout 4",
        surname: "fallout",
        price: "26.99",
        desc: 'Fallout 4 kể về hành trình của Sole Survivor trong việc tìm kiếm con trai bị mất tích trong một thế giới hậu tận thế.',
        link: 'https://fallout.bethesda.net/en/games/fallout-4',
        downloadLink: 'https://store.steampowered.com/app/377160/Fallout_4/',
        release: '10th of November, 2015',
        platforms: 'Xbox One, PlayStation 4, PC',
        genre: 'RPG',
        developers: 'Bethesda Game Studios',
        publishers: 'Bethesda Softworks',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 80,
        id: 18,
        cover: "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_500/v1658188603/fallout_kuxjw3.jpg",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658188603/fallout_kuxjw3.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658238100/fallout_1_b4smuk.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658238100/fallout_2_rlg0ng.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658238100/fallout_3_tc6vd8.jpg"
        ]
    },
    {
        name: "GTA: San Andreas",
        surname: "gtasanandreas",
        price: "3.99",
        desc: 'GTA: San Andreas theo chân Carl Johnson trong hành trình giành lại quyền kiểm soát các con phố của Los Santos.',
        link: 'https://www.rockstargames.com/games/sanandreas',
        downloadLink: 'https://play.google.com/store/apps/details?id=com.rockstargames.gtasa',
        release: '26th of October, 2004',
        platforms: 'Android, PlayStation 4, PlayStation 2, Xbox 360, Xbox, PC, PlayStation 3',
        genre: 'Action',
        developers: 'Rockstar North',
        publishers: 'Rockstar Games',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 90,
        id: 19,
        cover: "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_500/v1658188606/gtasanandreas_xkkyyp.jpg",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,w_1920/v1658188606/gtasanandreas_xkkyyp.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658238143/gtasanandreas_1_zah5ph.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658238142/gtasanandreas_2_vhvzyf.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658238143/gtasanandreas_3_pb1aih.jpg"
        ]
    },
    {
        name: "Golf with your Friends",
        surname: "golfwithyourfriends",
        price: "7.99",
        desc: 'Golf With Your Friends là một trò chơi golf mini vui nhộn, nơi người chơi có thể chơi cùng bạn bè.',
        link: 'http://www.blacklightinteractive.com/',
        downloadLink: 'https://store.steampowered.com/app/431240/Golf_With_Your_Friends/',
        release: '29th of January, 2016',
        platforms: 'Xbox One, PlayStation 4, Linux, PC, Nintendo Switch, Google Stadia',
        genre: 'Sports',
        developers: 'Blacklight Interactive',
        publishers: 'Team17 Digital / Blacklight Interactive',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 70,
        id: 20,
        cover: "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_500/v1658188609/golfwithyourfriends_rxrsbv.jpg",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658188609/golfwithyourfriends_rxrsbv.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658238166/golfwithyourfriends_1_hoq6ii.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658238166/golfwithyourfriends_2_zecdjb.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658238166/golfwithyourfriends_3_euuouh.jpg"
        ]
    },
    {
        name: "Heavy Rain",
        surname: "heavyrain",
        price: "23.99",
        desc: 'Heavy Rain là một trò chơi tâm lý kinh dị, nơi người chơi đưa ra các quyết định ảnh hưởng đến cốt truyện.',
        link: 'https://www.www.quanticdream.com/en/#!/en/category/heavy-rain',
        downloadLink: 'https://store.steampowered.com/app/960910/Heavy_Rain/',
        release: '18th of February, 2010',
        platforms: 'PlayStation 4, PC, PlayStation 3',
        genre: 'Puzzle',
        developers: 'Quantic Dream',
        publishers: 'Sony Computer Entertainment / Quantic Dream',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 82,
        id: 21,
        cover: "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_500/v1658188605/heavyrain_bljnwv.jpg",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658188605/heavyrain_bljnwv.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658238195/heavyrain_1_vvpszy.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658238195/heavyrain_2_f8y4rn.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658238196/heavyrain_3_fmkc8p.jpg"
        ]
    },
    {
        name: "Dota 2",
        surname: "dota",
        price: "12.99",
        desc: 'Dota 2 là một trò chơi chiến thuật thời gian thực, nơi hai đội cạnh tranh để phá hủy căn cứ của đối phương.',
        link: 'https://www.dota2.com/home',
        downloadLink: 'https://store.steampowered.com/app/570/Dota_2/',
        release: '9th of July, 2013',
        platforms: 'Linux, Mac, PC',
        genre: 'Strategy',
        developers: 'Valve',
        publishers: 'Valve',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 79,
        id: 22,
        cover: "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_500/v1658188603/dota_gdjxqx.jpg",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658188603/dota_gdjxqx.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658238225/dota_1_lld4aw.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658238227/dota_2_pguv1e.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658238225/dota_3_ef1lec.jpg"
        ]
    },
    {
        name: "Portal 2",
        surname: "portal2",
        price: "44.99",
        desc: 'Portal 2 là phần tiếp theo của Portal, nơi người chơi giải các câu đố bằng súng tạo cổng không gian.',
        link: 'https://www.thinkwithportals.com/',
        downloadLink: 'https://play.google.com/store/apps/details?id=com.valvesoftware.portal2companion',
        release: '19th of April, 2011',
        platforms: 'Linux, Xbox 360, Mac, PC, PlayStation 3',
        genre: 'Puzzle',
        developers: 'Valve',
        publishers: 'Valve',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 92,
        id: 23,
        cover: "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_500/v1658188606/portal2_eugfiq.jpg",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658188606/portal2_eugfiq.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658238290/portal2_1_tm6kyw.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658238290/portal2_2_kmrlol.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658238292/portal2_3_pjhzkj.jpg"
        ]
    },
    {
        name: "Sid Meier's Civilization VI",
        surname: "civilization",
        price: "27.99",
        desc: 'Sid Meier\'s Civilization VI là một trò chơi chiến lược theo lượt, nơi người chơi xây dựng một nền văn minh vượt thời gian.',
        link: 'https://www.civilization.com/',
        downloadLink: 'https://store.steampowered.com/app/289070/Sid_Meiers_Civilization_VI/',
        release: '20th of October, 2016',
        platforms: 'Xbox One, PlayStation 4, Linux, Mac, iOS, PC, Nintendo Switch',
        genre: 'Strategy',
        developers: 'Firaxis Games',
        publishers: '2K Games / Aspyr Media',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 82,
        id: 24,
        cover: "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_500/v1658188603/civilization_jcuqap.jpg",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658188603/civilization_jcuqap.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658238319/civilization_2_gpuqrk.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658238319/civilization_1_cc21ew.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658238318/civilization_3_qv8ben.jpg"
        ]
    },
    {
        name: "God of War",
        surname: "godofwar",
        price: "41.99",
        desc: 'God of War kể về hành trình của Kratos và con trai Atreus trong thế giới thần thoại Bắc Âu.',
        link: 'https://www.playstation.com/de-de/god-of-war/',
        downloadLink: 'https://store.steampowered.com/app/1593500/God_of_War/',
        release: '20th of April, 2018',
        platforms: 'PlayStation 4, PC',
        genre: 'Adventure',
        developers: 'Santa Monica Studio',
        publishers: 'Sony Interactive Entertainment',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 94,
        id: 25,
        cover: "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_500/v1658188602/godofwar_cbqzk1.jpg",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658188602/godofwar_cbqzk1.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658238374/godofwar_1_c7k5as.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658238373/godofwar_2_tiemyf.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658238377/godofwar_3_qohtw3.jpg"
        ]
    },
    {
        name: "FIFA 22",
        surname: "fifa",
        price: "15.99",
        desc: 'FIFA 22 mang đến trải nghiệm bóng đá chân thực với các đội bóng và cầu thủ nổi tiếng.',
        link: 'https://www.ea.com/de-de/games/fifa/fifa-22',
        downloadLink: 'https://store.steampowered.com/app/1506830/FIFA_22/',
        release: '30th of September, 2021',
        platforms: 'Xbox One, PlayStation 4, PlayStation 5, PC, Xbox Series S/X, Google Stadia',
        genre: 'Sports',
        developers: 'EA Vancouver / EA Romania',
        publishers: 'EA Sports',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 80,
        id: 26,
        cover: "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_500/v1658188603/fifa_zb6ook.jpg",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658188603/fifa_zb6ook.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658238407/fifa_1_tt7wm8.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658582251/fifa3_faiswk.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658238406/fifa_3_rwnx2k.jpg"
        ]
    },
    {
        name: "Half-Life 2",
        surname: "halflife",
        price: "11.99",
        desc: 'Half-Life 2 là một trò chơi bắn súng góc nhìn thứ nhất, nơi người chơi đối mặt với các thử thách và câu chuyện hấp dẫn.',
        link: 'https://www.half-life.com/en/halflife2',
        downloadLink: 'https://play.google.com/store/apps/details?id=com.valvesoftware.halflife2companion',
        release: '16th of November, 2004',
        platforms: 'Android, Linux, Xbox 360, Mac, Xbox, PC, PlayStation 3',
        genre: 'Shooter',
        developers: 'Valve',
        publishers: 'Valve',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 91,
        id: 27,
        cover: "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_500/v1658188604/halflife_fiorjc.jpg",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658188604/halflife_fiorjc.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658238448/halflife_1_nhsnrj.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658238448/halflife_2_wpnvmz.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658238450/halflife_3_xgil4x.jpg"
        ]
    },
    {
        name: "The Walking Dead: S1",
        surname: "twd",
        price: "6.99",
        desc: 'The Walking Dead: Season One (còn được gọi là The Walking Dead: The Game) là một trò chơi phiêu lưu tương tác, nơi người chơi đưa ra các quyết định ảnh hưởng đến cốt truyện.',
        link: 'http://www.thewalkingdeadgame.com/',
        downloadLink: 'https://play.google.com/store/apps/details?id=com.telltalegames.walkingdead100',
        release: '24th of April, 2012',
        platforms: 'Android, Xbox One, PlayStation 4, Xbox 360, PC, Nintendo Switch, PlayStation 3',
        genre: 'Adventure',
        developers: 'Telltale Games',
        publishers: 'Telltale Games',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 86,
        id: 28,
        cover: "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_500/v1658188600/twd_dmycxx.jpg",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658188600/twd_dmycxx.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658238474/twd_1_l4bv5v.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658238474/twd_2_m9rg9r.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658238474/twd_3_cclznv.jpg"
        ]
    },
    {
        name: "Crusader Kings III",
        surname: "crusaderkings",
        price: "22.99",
        desc: 'Crusader Kings III là một trò chơi chiến lược và mô phỏng triều đại, nơi người chơi phát triển một gia tộc qua nhiều thế kỷ.',
        link: 'https://www.paradoxinteractive.com/games/crusader-kings-iii/about',
        downloadLink: 'YOUR_DOWNLOAD_LINK_HERE',
        release: '1st of September, 2020',
        platforms: 'Linux, Mac, PlayStation 5, PC, Xbox Series S/X',
        genre: 'Strategy',
        developers: 'Paradox Development Studios',
        publishers: 'Paradox Interactive',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 85,
        id: 29,
        cover: "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_500/v1658188601/crusaderkings_fpz1te.jpg",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658188601/crusaderkings_fpz1te.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658238507/crusaderkings_1_m5wm5p.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658238507/crusaderkings_2_pmrmcc.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658238506/crusaderkings_3_hdzha4.jpg"
        ]
    },
    {
        name: "Counter Strike: GO",
        surname: "csgo",
        price: "4.99",
        desc: 'Counter-Strike: Global Offensive (CS:GO) là một trò chơi bắn súng góc nhìn thứ nhất, nơi hai đội cạnh tranh trong các trận đấu chiến thuật.',
        link: 'https://blog.counter-strike.net/',
        downloadLink: 'https://store.steampowered.com/app/730/CounterStrike_Global_Offensive/',
        release: '21st of August, 2012',
        platforms: 'Linux, Xbox 360, Mac, PC, PlayStation 3',
        genre: 'Shooter',
        developers: 'Valve / Hidden Path Entertainment',
        publishers: 'Valve',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 82,
        id: 30,
        cover: "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_500/v1658188600/csgo_o9whdd.jpg",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658188600/csgo_o9whdd.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658238547/csgo_1_gne318.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658238546/csgo_2_j1tgfo.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658238546/csgo_3_qgcwjw.jpg"
        ]
    },
    {
        name: "Detroit: Become Human",
        surname: "detroit",
        price: "65.99",
        desc: 'Detroit: Become Human là một trò chơi phiêu lưu tương tác, nơi người chơi khám phá các câu chuyện của ba nhân vật android.',
        link: 'https://www.www.quanticdream.com/en/detroit-become-human',
        downloadLink: 'https://store.steampowered.com/app/1222140/Detroit_Become_Human/',
        release: '25th of May, 2018',
        platforms: 'PlayStation 4, PC',
        genre: 'Puzzle',
        developers: 'Quantic Dream',
        publishers: 'Sony Interactive Entertainment / Quantic Dream',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 89,
        id: 31,
        cover: "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_500/v1658188602/detroit_a4kqkx.jpg",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658188602/detroit_a4kqkx.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658238582/detroit_1_i8im17.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658238582/detroit_2_yacxie.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658238578/detroit_3_truscr.jpg"
        ]
    },
    {
        name: "Tomb Raider",
        surname: "tombraider",
        price: "17.99",
        desc: 'Tomb Raider kể về hành trình của Lara Croft trong việc khám phá một hòn đảo bí ẩn và chiến đấu để sinh tồn.',
        link: 'https://tombraider.square-enix-games.com/en-us',
        downloadLink: 'https://store.steampowered.com/app/203160/Tomb_Raider/',
        release: '4th of March, 2013',
        platforms: 'Linux, Xbox 360, Mac, PC, PlayStation 3',
        genre: 'Adventure',
        developers: 'Crystal Dynamics',
        publishers: 'Square Enix Europe',
        inCart: false,
        selected: false,
        isHovered: false,
        isLiked: false,
        rating: 85,
        id: 32,
        cover: "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_500/v1658188613/tombraider_qx2xiy.jpg",
        footage: [
            "https://res.cloudinary.com/gianlucajahn/image/upload/c_scale,q_100,w_1920/v1658188613/tombraider_qx2xiy.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658238650/tombraider_1_jxeua4.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658238650/tombraider_2_fnhmmd.jpg",
            "https://res.cloudinary.com/gianlucajahn/image/upload/v1658238650/tombraider_3_cr0yee.jpg"
        ]
    },
]

export default games;